### ISSUE TITLE
Allow metadata 

### ISSUE THREAD

**Issue by imendes93** [lifebit-ai/pcgr-nf#27]
## Implementation

Allow metadata to be passed to the pcgr results:

- [x] combined tiers table
- [x] per gene summary table

Expected metadata format:

vcf | sample_id | histological_type | sex | library_name
-- | -- | -- | -- | --
G1.vcf | G1 | Germinoma | female | IGCT-1
G2.vcf | G2 | Germinoma | male | IGCT-3
G3.vcf | G3 | Germinoma | male | IGCT-4

with the VCF column matching the one from the csv input file

vcf
--
gs://cloudosinputdata/VCF.Files/G1.vcf
gs://cloudosinputdata/VCF.Files/G2.vcf
gs://cloudosinputdata/VCF.Files/G3.vcf

## Requirements

- [x] Present total number of samples for each metadata entry
- [x] Present  fraction of total samples for each metadata entry

Gene symbol | Gene_name | Tumor_suppressor | Oncogene | Number_Germinoma | Percent_Germinoma | Number_Nongerminoma | Percent_Nongerminoma
-- | -- | -- | -- | -- | -- | -- | --
JAK2 | Janus Kinase 2 | FALSE | TRUE | 2 | 0.4 | 0 | 0
EP300 | E1A Binding Protein P300 | TRUE | FALSE | 5 | 1 | 2 | 0.5
CREBBP | CREB Binding Protein | TRUE | FALSE | 4 | 0.8 | 1 | 0.25

**Comment by Vlad-Dembrovskyi** [comment]
After latest updates from Aaron on 13 Aug 2021:

Metadata will only be used in two places:
- To calculate total number and % of germinoma/nongerminoma/mixed samples that have mutations in particular gene in the first by-gene summary table (#29)
- all metadata fields added to original concatenated PCGR output table (#33)
