### ISSUE TITLE
Tier summary plot shows too many mutations

### ISSUE THREAD

**Issue by Vlad-Dembrovskyi** [lifebit-ai/pcgr-nf#48]
We see 12 Tier 3 mutations in by-tier summary plot, but only 6 in the by-variant table. It is because we show non-unique mutations in the plot, and unique mutations in the table. Because we have two identical samples in our test case, we have twice as much mutations in by-tier plot than in by-variant table. I don't know what is the number of mutations in other tables (unique or non-unique). 

I don't know what would be the desired requirement, but I think the number of mutations must be consistent across all plots and tables, otherwise its confusing. We'll need to ask on clarification on that. My hunch is that we have to show only the number of unique mutations in all plots and tables, but I'll clarify.

![image](https://user-images.githubusercontent.com/64809705/131357856-2fbaf299-4fa1-48a5-8580-03414fc63565.png)
![image](https://user-images.githubusercontent.com/64809705/131358081-a25178fe-d24b-4700-8ef0-e3a9341f79ab.png)
(pardon my drawings)

**Comment by imendes93** [comment]
@Vlad-Dembrovskyi any update on this?
