### ISSUE TITLE
Channel `data_bundle` has been used twice as an input by process `check_data_bundle` and another operator

### ISSUE THREAD

**Issue by cgpu** [lifebit-ai/pcgr-nf#61]
Cloned a formerly working job, this one https://cloudos.lifebit.ai/app/jobs/6167fc9d1b866a01d6982d64
![image](https://user-images.githubusercontent.com/38183826/143308543-63cca73e-1fb5-4eeb-b77d-e4b4d14374fc.png)

`commit: 3573406`
and got into this error:

https://cloudos.lifebit.ai/public/jobs/619e97a840695e01e73fd52d

![image](https://user-images.githubusercontent.com/38183826/143308414-b623dbd2-840f-4737-a533-be48cd57be80.png)
`commit also 3573406`

![image](https://user-images.githubusercontent.com/38183826/143308664-c33f84c8-74cd-4662-a5b5-5f99b61634ab.png)

**Comment by imendes93** [comment]
Issue could not be reproduced. 

- Cloned run using original working job (successful): https://cloudos.lifebit.ai/public/jobs/619f478e40695e01e7407fc3
- Cloned run of failed job (successful): https://cloudos.lifebit.ai/public/jobs/619f527440695e01e7409887

**Comment by cgpu** [comment]
closing as `cannot-reproduce`

**Comment by imendes93** [comment]
Added an additional two runs, who also ran successfully
